# Generated by Django 5.2.1 on 2025-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_produced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='produced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
